export const itemsTable = [
  {
    id: 1,
    item_name: 'Samsung split AC 1 ton',
    item_desc: "This is an item, isn't it?",
    brand: 'Samsung',
    quantity: 10,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: '',
  },
  {
    id: 2,
    item_name: 'LG refrigerator 300L',
    item_desc: 'Keeps your food fresh and cool.',
    brand: 'LG',
    quantity: 15,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Popular model',
  },
  {
    id: 3,
    item_name: 'Sony 42 inch LED TV',
    item_desc: 'High-definition television.',
    brand: 'Sony',
    quantity: 8,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Clearance sale item',
  },
  {
    id: 4,
    item_name: 'Panasonic microwave oven',
    item_desc: 'Convenient cooking solution.',
    brand: 'Panasonic',
    quantity: 20,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Customer favorite',
  },
  {
    id: 5,
    item_name: 'Whirlpool washing machine 7kg',
    item_desc: 'Efficient washing machine.',
    brand: 'Whirlpool',
    quantity: 12,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'New arrival',
  },
  {
    id: 6,
    item_name: 'Philips steam iron',
    item_desc: 'Smooth out wrinkles easily.',
    brand: 'Philips',
    quantity: 25,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Best seller',
  },
  {
    id: 7,
    item_name: 'Bose Bluetooth speaker',
    item_desc: 'Portable and powerful sound.',
    brand: 'Bose',
    quantity: 30,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'High demand',
  },
  {
    id: 8,
    item_name: 'Dyson vacuum cleaner',
    item_desc: 'Keep your home clean effortlessly.',
    brand: 'Dyson',
    quantity: 18,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Top-rated',
  },
  {
    id: 9,
    item_name: 'Canon DSLR camera',
    item_desc: 'Capture moments beautifully.',
    brand: 'Canon',
    quantity: 10,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Limited stock',
  },
  {
    id: 10,
    item_name: 'Apple MacBook Air',
    item_desc: 'Lightweight and powerful.',
    brand: 'Apple',
    quantity: 5,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Popular choice',
  },
  {
    id: 11,
    item_name: 'Samsung Galaxy S21',
    item_desc: 'Next-gen smartphone.',
    brand: 'Samsung',
    quantity: 20,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Latest model',
  },
  {
    id: 12,
    item_name: 'Nikon binoculars',
    item_desc: 'Perfect for bird watching.',
    brand: 'Nikon',
    quantity: 15,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Compact design',
  },
  {
    id: 13,
    item_name: 'KitchenAid stand mixer',
    item_desc: 'Baking made easy.',
    brand: 'KitchenAid',
    quantity: 10,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Highly recommended',
  },
  {
    id: 14,
    item_name: 'Logitech wireless mouse',
    item_desc: 'Smooth and precise control.',
    brand: 'Logitech',
    quantity: 50,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Affordable and reliable',
  },
  {
    id: 15,
    item_name: 'Fitbit Charge 4',
    item_desc: 'Track your fitness goals.',
    brand: 'Fitbit',
    quantity: 20,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Popular among athletes',
  },
  {
    id: 16,
    item_name: 'Garmin GPS Navigator',
    item_desc: 'Never get lost on the road.',
    brand: 'Garmin',
    quantity: 10,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Essential for road trips',
  },
  {
    id: 17,
    item_name: 'GoPro HERO9',
    item_desc: 'Capture adventures in 4K.',
    brand: 'GoPro',
    quantity: 12,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Perfect for action sports',
  },
  {
    id: 18,
    item_name: 'Nest Learning Thermostat',
    item_desc: 'Smart home climate control.',
    brand: 'Nest',
    quantity: 8,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Energy efficient',
  },
  {
    id: 19,
    item_name: 'Instant Pot Duo 7-in-1',
    item_desc: 'Multifunctional pressure cooker.',
    brand: 'Instant Pot',
    quantity: 22,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Highly versatile',
  },
  {
    id: 20,
    item_name: 'Roku Streaming Stick+',
    item_desc: 'Stream your favorite shows.',
    brand: 'Roku',
    quantity: 25,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Easy to use',
  },
  {
    id: 21,
    item_name: 'Seagate 2TB External Hard Drive',
    item_desc: 'Extra storage for your data.',
    brand: 'Seagate',
    quantity: 40,
    received_quantity: 0,
    damaged_quantity: 0,
    comment: 'Reliable and fast',
  },
];

export const columns = [
  // { field: 'id', headerName: 'ID' },
  { field: 'item_name', headerName: 'Item Name' },
  { field: 'item_desc', headerName: 'Description' },
  { field: 'brand', headerName: 'Brand' },
  { field: 'quantity', headerName: 'Quantity' },
  {
    field: 'received_quantity',
    headerName: 'Received Quantity',
    isEdit: true,
    type: 'number',
  },
  {
    field: 'damaged_quantity',
    headerName: 'Damaged Quantity',
    isEdit: true,
    type: 'number',
  },
  { field: 'comment', headerName: 'Comment', isEdit: true },
];
